project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: index.qmd
        text: "Academic and Certifications"
      - href: index.qmd
        text: "Professional"
      - href: index.qmd
        text: "Projects"
  page-footer: "© 2026 kim-vr"

format:
  html:
    theme: darkly
    toc: true

execute:
  freeze: auto

# Configuration for GitHub Pages
publish:
  provider: "github"
  branch: "main"