project:
  type: website
  output-dir: docs

website:
  title: "Portfolio test"
  navbar:
    left:
      - href: index.qmd
        text: "All my projects will be cited below"
  page-footer: "© 2026 kim-vr"

format:
  html:
    theme: quartz
    toc: true

execute:
  freeze: auto

# Configuration for GitHub Pages
publish:
  provider: "github"
  branch: "main"