project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: photogrammetry.qmd
        text: "Photogrammetry demo"
      - href: index.qmd
        text: "Academic and Certifications"
      - href: index.qmd
        text: "Professional"
      - href: index.qmd
        text: "Projects"
  page-footer: "© 2026 kim-vr"

format:
  html:
    theme: 
      dark: 
        - darkly
        - content/custom.scss
      light: 
        - sketchy
        - content/custom.scss
    toc: true

execute:
  freeze: auto

# Configuration for GitHub Pages
publish:
  provider: "github"
  branch: "main"